#!/usr/bin/env bash

rm repositories/ubuntu/python-vmware-dvs*
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin


git clone git@github.com:Mirantis/vmware-dvs.git -b liberty
cd vmware-dvs
make
cp *.deb ../repositories/ubuntu

cd ..
rm -rf vmware-dvs
